### ISSUE TITLE
Player can create a Character

### ISSUE THREAD

**Issue by macekond** [platejan/HeroCamp#6]
character has:
name
bio (description)

**Comment by macekond** [comment]
Character name is unique within player's characters

**Comment by platejan** [comment]
Need add rules to Firebase which check following terms...
If ownerID in new hero is set to current user.

**Comment by platejan** [comment]
Firebase rules must contain term which enable deleting & updating only for owner of each character.

**Comment by platejan** [comment]
Added rules to Firebase -> view, update, delete is allowed only for owner

**Comment by macekond** [comment]
Character name shouldn't be unique.
